### ISSUE TITLE
Assumption in ManifestBuilder

### ISSUE THREAD

**Issue by jcarroll-mediafly** [thomaschristensen/Pantomime#1]
In the parse method I like how it can parse the master and recursively the media playlists it finds.

However, the `url.URLByReplacingLastPathComponent` assumes the video variant playlist url is relative to the base url. It is technically possible for the variant to be a fully qualified url in which case it should simply use that URL.

**Comment by jcarroll-mediafly** [comment]
On an unrelated note; I enjoy the project so far. There isn't much out there and excited to see where this goes. And once I get some free time I'm likely to contribute on things such as this. :) 

Dealing with subtitles, modifying the playlist at a finer grain level, and like you said being able to write to disk are all exciting things I'd personally be interested in.

**Comment by thomaschristensen** [comment]
I see your point and agree that the parsing should be able to handle both situations ie. the explicit full URL and the relative.

**Comment by thomaschristensen** [comment]
It would be great to collaborate on enhancing this library.

**Comment by thomaschristensen** [comment]
Latest commit solves this by checking for protocol in the URL strings parsed. In case of the protocol has been specified it's assumed that the path will be fully specified.
