### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by sarah-a-jaafar** [thomaschristensen/Pantomime#3]
When will this project supports Swift 3?
Thanks in advance :) .

**Comment by thomaschristensen** [comment]
Converting the source to swift 3 is straight forward. Unfortunately it breaks the binary compatibility with programs based on swift 2.3, but eventually swift 3 is the way forward.
Most changes are just minor renaming of 
public -> open
private -> fileprivate
NSData -> Data
NSURL -> URL
etc. 
So not complex.
Let me know if this is required.

**Comment by thomaschristensen** [comment]
Actually on https://github.com/jcarroll-mediafly/Pantomime there is already support for swift 3.

**Comment by sarah-a-jaafar** [comment]
Thank you very much :) .
👍
